apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ BRAND_NAME }}-vikings-logs-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
