apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ BRAND_NAME }}-vikings-logs-pvc
spec:
  storageClassName: {{ STORAGE_CLASS }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ STORAGE_SIZE }}
