apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ BRAND_NAME }}-vikings-static-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
