apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ BRAND_NAME }}-vikings-cm
data:
  VIKINGS_APP_NAME: '{{ VIKINGS_APP_NAME }}'
  DEBUG: 'False'
  DB_TYPE: 'mysql'
  DEFAULT_USER: '{{ BRAND_NAME }}'
  DEFAULT_USER_MAIL: '{{ HOST_EMAIL }}'
  VIKINGS_HOST: '{{ HOST }}'
