apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ BRAND_NAME }}-vikings-cm
data:
  DEBUG: 'False'
  DB_HOST: mariadb.central-svcs.svc.cluster.local
  DB_PORT: '3306'
  DB_TYPE: 'mysql'
  DB_NAME: '{{ DB_NAME }}'
  DEFAULT_USER: '{{ BRAND_NAME }}'
  DEFAULT_USER_MAIL: '{{ HOST_EMAIL }}'
  VIKINGS_HOST: '{{ HOST }}'
