apiVersion: batch/v1
kind: Job
metadata:
  name: {{ BRAND_NAME }}-vikings-postgres-dropdb
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: {{ BRAND_NAME }}-vikings-postgres-dropdb
          image: postgres:13.3
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ BRAND_NAME }}-vikings-postgres-cm
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ BRAND_NAME }}-vikings-postgres-cm
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ BRAND_NAME }}-vikings-postgres-secret
                  key: DB_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ BRAND_NAME }}-vikings-postgres-secret
                  key: DB_PASS
          command: ["dropdb"]
          args: ["-h", "$(DB_HOST)", "-U", "$(DB_USER)", "$(DB_NAME)"]
      restartPolicy: Never
  backoffLimit: 1