apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vikings-cm
  labels:
    {{- include "vikings.labels" . | nindent 4 }}
data:
  VIKINGS_HOST: {{ .Values.vikings.domain | toString | quote }}
  DEBUG: {{ .Values.vikings.debug | toString | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vikings-site-config.conf
  labels:
    {{- include "vikings.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    {{- include "vikings.site-config-conf" . | toString | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vikings-main.css
  labels:
    {{- include "vikings.labels" . | nindent 4 }}
data:
  main.css: |-
    {{- if not .Values.vikings.css }}
    {{- include "vikings.main-css" . | toString | nindent 4 }}
    {{- else }}
    {{ .Values.vikings.css | toString | nindent 4 | trim }}
    {{- end }}
{{- if .Values.vikings.logo }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vikings-logo.png
  labels:
    {{- include "vikings.labels" . | nindent 4 }}
binaryData:
  logo.png: |-
    {{ .Values.vikings.logo | toString | replace " " "" | nindent 4 | trim }}
{{- end }}
{{- if .Values.vikings.favicon }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vikings-favicon.ico
  labels:
    {{- include "vikings.labels" . | nindent 4 }}
binaryData:
  favicon.ico: |-
    {{ .Values.vikings.favicon | toString | replace " " "" | nindent 4 | trim }}
{{- end }}
{{- if .Values.vikings.background }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vikings-background.jpg
  labels:
    {{- include "vikings.labels" . | nindent 4 }}
binaryData:
  background.jpg: |-
    {{ .Values.vikings.background | toString | replace " " "" | nindent 4 | trim }}
{{- end }}
