apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-vikings-logs-pvc
  labels:
    {{- include "vikings.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.logs.storage }}
  storageClassName: {{ .Values.pvc.logs.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-vikings-core-migrations-pvc
  labels:
    {{- include "vikings.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.migrations.storage }}
  storageClassName: {{ .Values.pvc.migrations.storageClassName }}
