# mariadb
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ BRAND_NAME }}-vikings-database-dropdb
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: {{ BRAND_NAME }}-vikings-database-dropdb
          image: bitnami/mariadb-galera:10.5.11-debian-10-r24
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ BRAND_NAME }}-vikings-database-cm
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ BRAND_NAME }}-vikings-database-cm
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ BRAND_NAME }}-vikings-database-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ BRAND_NAME }}-vikings-database-secret
                  key: DB_PASS
          command: ["mysqladmin"]
          args: ["-h", "$(DB_HOST)", "-u", "$(DB_USER)", "-p$(DB_PASS)", "drop", "-f", "$(DB_NAME)"]
      restartPolicy: Never
  backoffLimit: 1